name: layoff-lens
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - altair
  - vl-convert-python
  - jupyterlab
  - ipykernel
  - pip
  - pip:
    - shiny
    - shinywidgets